# CONDA ENVIRONMENT FILE
name: nf-training
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow=23.04.1
  - nf-core
  - R
  - bwa=0.7.17
  - fastp
  - samtools=1.17
  - kallisto
  - salmon
  - fastqc
  - multiqc
